language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.6
      env: TOX_ENV=docs
    - python: 3.6
      env: TOX_ENV=lint
    - python: 3.6
      env: TOX_ENV=manifest

install: pip install tox
script: tox -e $TOX_ENV

# Control the branches that get built.
branches:
  only:
    - master
